### PR TITLE
Change config file priority

### PR DESCRIPTION
**Pull request by jordonbaade**
Changes config file priority so that configurationFile comes first if option.configurationFile is set, and gulp.src() second only if option.configurationFile is not set.

My solution to: https://github.com/laravel/elixir/issues/229

### CODE REVIEW

**Comment by mikeerickson** [comment]
@jordonbaade Can you please provide a little bit more information about this issue.  I hear what you are saying (about moving config file up on priority chain). but I am still unclear exactly what the exact issue is.   I have to think about applying this to the core modules I use for all gulp-xxxx plugins (ie phpspec, behat, and codeception).

While it appears to be an isolated issue with regards to PHPUnit, I still want to know what is happening as gulp.src is basically an entrypoint into the plugin, but the actual code does not use the src files?

**Comment by jordonbaade** [comment]
I'm new, so I'll try.

Basically the core issue I see is that this line:

https://github.com/mikeerickson/gulp-phpunit/blob/master/index.js#L180

Is impossible to get to because of this line: 
https://github.com/mikeerickson/gulp-phpunit/blob/master/index.js#L175

Correct me if I'm wrong, but gulp.src() should always have an argument of files passed to it, otherwise it throws a fit.  This means that a configurationFile can never be loaded as it stands, because there is always something in gulp.src() and that takes priority over everything as long as noConfiguration isn't set, but gulp.src() is not always the xml file as seen with Elixir.

Elixir is passing a string pattern for the test files from:
https://github.com/laravel/elixir/blob/master/tasks/phpunit.js#L21
to: 
https://github.com/laravel/elixir/blob/master/tasks/shared/Tests.js#L13

It would seem this Elixir file was written prior to this commit which introduced pulling from gulp.src:
https://github.com/mikeerickson/gulp-phpunit/commit/2b8ac6c1e14f9beeb662aa86c666b83e3b232ce1

Jeffrey could probably change it so that there is a separate option in phpunit.js for the watch pattern,  and update the gulp.src() to work with that last commit, but in the interest of keeping everything simple & flexible, and seeing that gulp-phpunit didn't seem (to me) to allow use of a configuration file through it's own option.configurationFile I thought this was a good route.

**Comment by mikeerickson** [comment]
@jordonbaade I will get this cleared up this weekend for sure.  Will aim to complete tomorrow, but have lots on my weekend plate, so Sunday at latest :)

**Comment by jordonbaade** [comment]
Let me know if I can do anything to help out. :)

**Pull request closed without merging**
